[tool.poetry]
name = "sample"
version = "0.1.0"
description = ""
authors = ["gepuro <gepuro@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
black = "^19.10b0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
